### ISSUE TITLE
Rails --api mode when ?

### ISSUE THREAD

**Issue by thegreyfellow** [brunofacca/zen-rails-base-app#7]
I was just wondering if you guys are thinking of handeling rails api mode and what are the plans for that ? 
Thanks

**Comment by brunofacca** [comment]
There are no plans to transform this into an API-only application (Rails API mode). You could make it API-only by following [these steps](https://hashrocket.com/blog/posts/how-to-make-rails-5-api-only). However, you would have to remove many components that would not be used in an API, such as the HTML templates and assets such as JS, SCSS. You would also have to rewrite the controllers to return JSON instead of rendering web views. In short, I'm not sure it would be worth it. You're probably better off starting a new project from scratch and only using bits and pieces of this application, such as parts of the Gemfile and the testing environment setup at `spec/`.
